### ISSUE TITLE
PUID and PGID issues

### ISSUE THREAD

**Issue by flowlee** [mod242/docker-easyepg#3]
It seems like the PUID and PGID parameters are not respected when running `docker exec -it easyepg /bin/bash` to set up the application for the first time. This results in all files created by the easyepg script being owned by the root user/group on the host system.

**Comment by mod242** [comment]
Hi flowlee,

if you run it by /defaults/epgupgrade.sh to set up the application (that's the script that's called by cron later on anyway) the correct permissions should be applied. Can you try this? I'll make this clear in the documentation then.
