### ISSUE TITLE
cron seems not to work

### ISSUE THREAD

**Issue by torwag** [mod242/docker-easyepg#5]
Hi,
I can start the update manually (within the container) and it seems to work restarting the container.
However, the cronjob seems not to work.
ee-cron:
`
2 3 * * * /bin/bash /defaults/epgupdate.sh
`
Logs do not show any problem.
I changed the cron log now to -l 6 and now I get 
`easyepg     | 2019-10-02T17:07:13.336926805Z cron: can't lock /var/run/crond.pid, otherpid may be 692: Resource temporarily unavailable`
every second

Is there any other way to debug this?

**Comment by mod242** [comment]
Hi,
I am very sorry, just noticed this issue (somehow the notification didn't trigger). Did you resolve the issue, or does it still happen that the cronjob isn't working?
