### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by halfagascan** [mod242/docker-easyepg#6]
Linux me 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux
Docker version 19.03.5, build 633a0ea838

Following install instructions from:
https://hub.docker.com/r/qoopido/easyepg.minimal

Results in:
me@me:~/easyepg$ docker exec -ti -u easyepg -w /easyepg easyepg.admin /bin/bash ./epg.sh
/bin/bash: ./epg.sh: No such file or directory

ls -all as root:
root@17bbad1e6fc2:/# ls -all
total 108
drwxr-xr-x   1 root    root    4096 Jan 16 07:31 .
drwxr-xr-x   1 root    root    4096 Jan 16 07:31 ..
drwxr-xr-x   1 root    root    4096 Jan 14 13:39 bin
drwxr-xr-x   2 root    root    4096 Sep  8 05:51 boot
drwxr-xr-x   5 root    root     340 Jan 16 07:35 dev
-rwxr-xr-x   1 root    root       0 Jan 16 07:31 .dockerenv
drwxr-xr-x   2 easyepg easyepg 4096 Jan 16 07:28 easyepg
-rw-r--r--   1 root    root      97 Jan 14 13:37 easyepg.cron
-rwxr-xr-x   1 root    root     223 Jan 14 13:37 easyepg.install.sh
-rwxr-xr-x   1 root    root     289 Jan 14 13:37 easyepg.update.sh
-rwxr-xr-x   1 root    root    1430 Jan 14 13:37 entrypoint.sh
drwxr-xr-x   1 root    root    4096 Jan 16 07:35 etc
drwxr-xr-x   2 root    root    4096 Sep  8 05:51 home
drwxr-xr-x   1 root    root    4096 Jan 14 13:44 lib
drwxr-xr-x   2 root    root    4096 Dec 23 18:00 lib64
drwxr-xr-x   2 root    root    4096 Dec 23 18:00 media
drwxr-xr-x   2 root    root    4096 Dec 23 18:00 mnt
drwxr-xr-x   2 root    root    4096 Dec 23 18:00 opt
-rwxr-xr-x   1 root    root     125 Jan 14 13:37 packages.cleanup.sh
-rwxr-xr-x   1 root    root      88 Jan 14 13:37 packages.install.sh
dr-xr-xr-x 205 root    root       0 Jan 16 07:35 proc
-rwxr-xr-x   1 root    root     607 Jan 14 13:37 process.sh
drwx------   1 root    root    4096 Jan 16 07:37 root
drwxr-xr-x   3 root    root    4096 Dec 23 18:00 run
drwxr-xr-x   1 root    root    4096 Jan 14 13:39 sbin
drwxr-xr-x   2 root    root    4096 Dec 23 18:00 srv
dr-xr-xr-x  13 root    root       0 Jan 15 12:18 sys
drwxrwxrwt   2 easyepg easyepg   40 Jan 16 07:35 tmp
drwxr-xr-x   1 root    root    4096 Dec 23 18:00 usr
drwxr-xr-x   1 root    root    4096 Dec 23 18:00 var
srwxr-xr-x   1 easyepg    1000    0 Jan 15 13:05 xmltv.sock

root@17bbad1e6fc2:/# ls -all easyepg/
total 12
drwxr-xr-x 2 easyepg easyepg 4096 Jan 16 07:28 .
drwxr-xr-x 1 root    root    4096 Jan 16 07:31 ..
-rw------- 1 easyepg easyepg  182 Jan 16 07:36 .bash_history

**Comment by mod242** [comment]
Hi, this seems to be another image (https://hub.docker.com/r/qoopido/easyepg.minimal), if i am coreect
